### PR TITLE
Source bash profile in gcloud_install to fix #140

### LINKED ISSUE #140: `gcloud_install()` requires two runs in linux systems
Running `gcloud_install()` modifies the `.bash_profile`:

screen shot 2018-04-10 at 3 09 22 pm

to which when `cloudml` runs `glcoud init` fails since `gcloud` is not in the PATH yet.

### PR DESCRIPTION
**Pull request by javierluraschi**
See #140, sourcing the bash profile is required to avoid having to call `gcloud_install()` twice in Linux systems.

### CODE REVIEW

File: R/gcloud-install.R [hunk 1]
```diff
@@ -99,7 +99,7 @@ gcloud_install_unix <- function() {
                               paste0("--install-dir=",
                                      path.expand(dirname(gcloud_binary))))),
                           collapse = " ")
-    terminal_command <- paste(install_args, "&&", "gcloud", "init")
+    terminal_command <- paste(install_args, "&&", "source", "~/.bash_profile", "&&", "gcloud", "init")
```
Comment (jjallaire) [inline R/gcloud-install.R]: If there is no ~/.bash_profile will the gcloud init still occur?

Comment (javierluraschi) [reply R/gcloud-install.R]: It won't, updating with a bit better fix.
